import { chromium } from 'playwright'
const EXE = process.env.PW_CHROME || ''
const results = []
function check(name, cond) { results.push({ name, ok: !!cond }); console.log((cond ? 'PASS' : 'FAIL') + ' · ' + name) }
const browser = await chromium.launch(EXE ? { executablePath: EXE } : {})
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', e => console.log('PAGEERROR', e.message))
await page.goto('http://127.0.0.1:8899/')
await page.waitForSelector('.chip', { timeout: 8000 })

check('팔레트 렌더', (await page.locator('.chip').count()) > 0)
const seeded = await page.locator('.fitem').count()
check('초기 시드 페이지(3)', seeded === 3)

await page.locator('.chip', { hasText: '로드맵' }).first().click()
check('카드 추가(+1)', (await page.locator('.fitem').count()) === seeded + 1)

const inp = page.locator('.fld input').first()
await inp.fill('스모크 제목')
await page.waitForTimeout(200)
check('편집 → 미리보기 반영', (await page.locator('.stage').innerText()).includes('스모크 제목'))

await page.locator('.seg button', { hasText: '가로 덱' }).click()
check('가로 전환', (await page.locator('.pv-cap').innerText()).includes('가로 덱'))
await page.locator('.seg button', { hasText: '세로 이북' }).click()

await page.click('[data-tut="tool-box"]')
await page.locator('.stage .freelayer').click({ position: { x: 120, y: 120 } })
await page.waitForTimeout(150)
check('자유 캔버스 도형 추가', (await page.locator('.stage .fel').count()) >= 1)
await page.click('[data-tut="tool-box"]')
await page.locator('.stage .freelayer').click({ position: { x: 300, y: 320 } })
await page.waitForTimeout(150)
check('도형 2개', (await page.locator('.stage .fel').count()) >= 2)

await page.click('[data-tut="tool-connect"]')
await page.locator('.stage .fel').nth(0).click()
await page.locator('.stage .fel').nth(1).click()
await page.waitForTimeout(150)
check('연결선 생성(화살표)', (await page.locator('.stage .freeconn path[marker-end]').count()) >= 1)

await page.click('[data-tut="tool-pen"]')
const fl = await page.locator('.stage .freelayer').boundingBox()
await page.mouse.move(fl.x + 60, fl.y + 200); await page.mouse.down()
await page.mouse.move(fl.x + 120, fl.y + 230); await page.mouse.move(fl.x + 180, fl.y + 210); await page.mouse.up()
await page.waitForTimeout(150)
check('펜 자유선', (await page.locator('.stage .freeconn path[stroke-linecap="round"]').count()) >= 1)

// 타이포그래피 전환
await page.locator('.ty select').nth(0).selectOption({ label: '명조' })
await page.waitForTimeout(120)
check('폰트 전환 반영', (await page.locator('.pv-cap').innerText()).includes('커스텀 폰트'))
await page.locator('.ty select').nth(1).selectOption({ label: '크게' })
await page.waitForTimeout(120)
check('글자 크기 전환 반영', (await page.locator('.pv-cap').innerText()).includes('크게'))
// 문구 다듬기
await page.locator('.fld input').first().fill('  많은   공백   ')
await page.click('.polish-btn')
await page.waitForTimeout(120)
check('문구 다듬기(공백 정리)', (await page.locator('.fld input').first().inputValue()) === '많은 공백')
// 이미지 요소 추가
await page.click('[data-tut="tool-image"]')
await page.locator('.stage .freelayer').click({ position: { x: 210, y: 360 } })
await page.waitForTimeout(120)
check('이미지 요소 추가', (await page.locator('.stage .fel.image').count()) >= 1)
await page.click('[data-tut="tool-select"]')

// --- 키보드 단축키 ---
await page.locator('.stage .fel').first().click()
await page.waitForTimeout(80)
const beforeDup = await page.locator('.stage .fel').count()
await page.keyboard.press('Control+d')
await page.waitForTimeout(120)
check('단축키 복제(⌘/Ctrl+D)', (await page.locator('.stage .fel').count()) === beforeDup + 1)
await page.keyboard.press('Delete')
await page.waitForTimeout(120)
check('단축키 삭제(Delete)', (await page.locator('.stage .fel').count()) === beforeDup)
await page.keyboard.press('Control+z')
await page.waitForTimeout(120)
check('단축키 되돌리기(⌘/Ctrl+Z)', (await page.locator('.stage .fel').count()) === beforeDup + 1)
await page.keyboard.press('Control+Shift+z')
await page.waitForTimeout(120)
check('단축키 다시 실행(⌘/Ctrl+⇧+Z)', (await page.locator('.stage .fel').count()) === beforeDup)
// 방향키 이동
const nEl = page.locator('.stage .fel').first()
await nEl.click(); await page.waitForTimeout(80)
const nb1 = await nEl.boundingBox()
await page.keyboard.press('Shift+ArrowRight'); await page.keyboard.press('Shift+ArrowRight'); await page.keyboard.press('Shift+ArrowRight')
await page.waitForTimeout(120)
const nb2 = await nEl.boundingBox()
check('단축키 방향키 이동', !!(nb1 && nb2 && nb2.x > nb1.x))
// 도구 단축키
await page.keyboard.press('r')
await page.waitForTimeout(60)
check('도구 단축키(R=사각형)', (await page.locator('[data-tut="tool-box"].on').count()) === 1)
await page.keyboard.press('v')

await page.click('.manual-btn')
check('설명서 패널', (await page.locator('.manual-panel .mrow').count()) > 5)
await page.click('.manual-panel .close')

await page.locator('.help-btn', { hasText: '도움말' }).click()
await page.click('.help-tut-btn')
check('튜토리얼 코치 표시', await page.locator('.coach').isVisible())
check('튜토리얼 스포트라이트 링', (await page.locator('.tut-ring').count()) >= 1)
await page.locator('.coach .coach-x').click()

await page.click('.make')
await page.waitForTimeout(4000)
const status = await page.locator('.tb-status').innerText().catch(() => '')
check('이북 만들기(모의 API 완료)', status.includes('완료') || (await page.locator('.tb-status a').count()) >= 1)

await page.click('.present-btn')
check('발표 모드 진입', await page.locator('.present').isVisible())
await page.keyboard.press('ArrowRight'); await page.waitForTimeout(150)
await page.keyboard.press('Escape'); await page.waitForTimeout(150)
check('발표 모드 종료(Esc)', (await page.locator('.present').count()) === 0)

// ===== 2차 기능 (환경설정 · 챗 · 토글 · 예시영상 · 액션) =====
await page.locator('.help-btn', { hasText: '환경설정' }).click()
await page.waitForSelector('.settings-card', { timeout: 4000 })
check('환경설정 모달 열림', await page.locator('.settings-card').isVisible())
check('환경설정 provider 로딩', (await page.locator('.settings-grid select').first().inputValue()) === 'self')
await page.locator('.settings-modal .close').click()
await page.waitForTimeout(200)

await page.locator('.chat-fab').click()
await page.waitForSelector('.chat-panel.open', { timeout: 4000 })
await page.locator('.chat-panel footer input').fill('안녕')
await page.locator('.chat-panel footer input').press('Enter')
await page.waitForTimeout(1200)
check('챗 대화 응답(스트리밍)', (await page.locator('.chat-bubble.assistant').count()) >= 2)
const preAct = await page.locator('.fitem').count()
await page.locator('.chat-panel footer input').fill('성과 카드 넣어줘')
await page.locator('.chat-panel footer input').press('Enter')
await page.waitForTimeout(1300)
check('챗 액션 브리지(카드 추가)', (await page.locator('.fitem').count()) === preAct + 1)
await page.locator('.chat-header-actions button').last().click()
await page.waitForTimeout(200)

await page.locator('.chip', { hasText: '빈 페이지' }).click()
await page.waitForSelector('.block-editor', { timeout: 4000 })
check('블록·토글 에디터', await page.locator('.block-editor').isVisible())
check('블록 미리보기 렌더', (await page.locator('.stage').innerText()).includes('새 페이지 제목'))
// 슬래시 메뉴로 토글 생성
await page.locator('.be-addblock').click()
await page.waitForTimeout(120)
const nta = page.locator('.be-ta').last()
await nta.click(); await nta.pressSequentially('/')
await page.waitForTimeout(150)
check('블록 슬래시 메뉴', await page.locator('.be-menu').isVisible())
await page.locator('.be-menu button', { hasText: '토글' }).click()
await page.waitForTimeout(120)
check('토글 블록 생성', (await page.locator('.be-arrow').count()) >= 1)

await page.locator('.help-btn', { hasText: '예시영상' }).click()
await page.waitForSelector('.demo-bar', { timeout: 4000 })
check('예시영상 재생 시작', await page.locator('.demo-bar').isVisible())
await page.locator('.demo-btn.close').click()
await page.waitForTimeout(500)
check('예시영상 종료·복원', (await page.locator('.demo-bar').count()) === 0)

await browser.close()
const passed = results.filter(r => r.ok).length
console.log('\n=== ' + passed + '/' + results.length + ' PASS ===')
process.exit(passed === results.length ? 0 : 1)
