"""이북 도메인 의도 스키마 — 분류기·슬롯·액션매퍼가 공유하는 정본.

HELIX의 CompiledSchema(measures/dimensions 중심) 대신, 편집 명령 어휘를 담는다.
"""
from __future__ import annotations

from server.intent.schemas import EbookSchema, IntentSpec

EBOOK_SCHEMA = EbookSchema(intents=[
    IntentSpec("add_slide", "새 슬라이드",
               keywords=["새 슬라이드", "슬라이드 추가", "페이지 추가", "장 추가", "슬라이드 하나", "빈 슬라이드"],
               high_signal=r"(새\s*슬라이드|슬라이드\s*(추가|하나|한\s*장)|페이지\s*추가)"),
    IntentSpec("duplicate_slide", "슬라이드 복제",
               keywords=["슬라이드 복제", "슬라이드 복사", "이 장 복제", "페이지 복제", "똑같이 하나"],
               high_signal=r"(슬라이드|페이지|이\s*장).{0,4}(복제|복사)"),
    IntentSpec("delete_slide", "슬라이드 삭제",
               keywords=["슬라이드 삭제", "페이지 삭제", "이 장 지워", "슬라이드 지워", "이 슬라이드 삭제"],
               high_signal=r"(슬라이드|페이지|이\s*장).{0,4}(삭제|지워|없애)"),
    IntentSpec("delete_element", "도형 삭제",
               keywords=["도형 삭제", "지워", "없애", "치워", "제거"],
               high_signal=r"(삭제|지워|지우|없애|없앤|치워|제거|클리어|업애)"),
    IntentSpec("insert_text", "텍스트 상자",
               keywords=["텍스트", "글상자", "글자 추가", "제목 넣", "문구 넣"],
               high_signal=r"(텍스트\s*(상자|박스)?|글상자|글자).{0,4}(추가|넣|삽입|만들)"),
    IntentSpec("insert_shape", "도형",
               keywords=["도형", "사각형", "네모", "동그라미", "타원", "마름모", "삼각형"],
               high_signal=r"(사각형|네모|동그라미|타원|마름모|삼각형|도형).{0,5}(추가|넣|삽입|그려|만들)?|(?<![가-힣])원(?=[\s\d을를이가]|$).{0,4}(추가|넣|삽입|그려|만들|놓)"),
    IntentSpec("insert_arrow", "화살표",
               keywords=["화살표", "연결선", "연결"],
               high_signal=r"(화살표|연결선).{0,4}(추가|넣|삽입|그려)?"),
    IntentSpec("insert_table", "표",
               keywords=["표 추가", "표 넣", "테이블", "표 삽입", "표 그려"],
               # '발표·목표·도표·그래프' 안의 '표'에 오탐하지 않도록 앞 글자 배제
               high_signal=r"(?<![발목도차그림])표(?!지).{0,4}(추가|넣|삽입|그려|만들)|테이블"),
    IntentSpec("insert_image", "이미지",
               keywords=["이미지", "그림", "사진", "이미지 넣"],
               high_signal=r"(이미지|그림|사진).{0,4}(추가|넣|삽입)"),
    IntentSpec("insert_wordart", "글맵시",
               keywords=["글맵시", "워드아트", "wordart", "꾸민 글자"],
               high_signal=r"(글맵시|워드아트|word\s*art)"),
    IntentSpec("set_theme", "배경/테마",
               keywords=["다크", "어둡게", "라이트", "밝게", "배경", "어두운", "밝은"],
               high_signal=r"(다크|어둡게|어두운|라이트|밝게|밝은|배경).{0,4}(으로|해|바꿔|모드)?"),
    IntentSpec("set_orientation", "방향 전환",
               keywords=["가로", "세로", "가로 덱", "세로 이북"],
               high_signal=r"(가로|세로).{0,4}(덱|이북|으로|로|바꿔|전환|변경|해)"),
    IntentSpec("import_html", "HTML 가져오기",
               keywords=["html 가져", "가져오기", "불러오기", "임포트", "html 불러", "html 변환"],
               high_signal=r"(html).{0,4}(가져|불러|변환|임포트)|가져오기|불러오기"),
    IntentSpec("make_ebook", "이북(PDF) 만들기",
               keywords=["이북 만들", "pdf", "출간", "책 만들", "이북 생성", "뽑아"],
               high_signal=r"(이북|pdf|책).{0,4}(만들|생성|출간|제작|뽑)"),
    IntentSpec("z_order", "맨 앞/뒤",
               keywords=["맨 앞", "맨 뒤", "앞으로", "뒤로", "위로 올려", "아래로 내려"],
               high_signal=r"(맨\s*앞|맨\s*뒤|앞으로|뒤로|위로\s*올려|아래로\s*내려)"),
    IntentSpec("present", "슬라이드쇼",
               keywords=["슬라이드쇼", "프레젠테이션", "전체화면", "발표 시작", "발표 모드"],
               # '발표자료' 처럼 뒤에 명사가 붙으면 제외, 발표+동작일 때만
               high_signal=r"(슬라이드\s*쇼|프레젠|전체\s*화면|발표\s*(모드|시작|해|하기|하자|할래|할게))"),
    IntentSpec("undo", "실행취소",
               keywords=["실행취소", "되돌려", "되돌리기", "취소해", "방금 취소"],
               high_signal=r"(실행\s*취소|되돌려|되돌리기|방금.{0,3}취소)"),
    IntentSpec("redo", "다시실행",
               keywords=["다시실행", "다시 해", "재실행", "다시 살려"],
               high_signal=r"(다시\s*실행|재실행|다시\s*살려)"),
    IntentSpec("help", "사용법",
               keywords=["도움", "사용법", "어떻게", "뭐 할 수", "뭘 할", "방법", "기능"],
               high_signal=r"(사용법|어떻게\s*(써|해|만들)|뭐\s*할\s*수|뭘\s*할|도와)"),
    IntentSpec("smalltalk", "인사",
               keywords=["안녕", "반가", "고마", "감사", "hi", "hello", "ㅎㅇ"],
               high_signal=r"^(안녕|반가|고마|감사|hi|hello|ㅎㅇ)"),
])
